version: "3.9"

services:

  selenium-hub:
    image: selenium/hub:4.34.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - SE_GRID_MAX_SESSION=10
      - SE_GRID_BROWSER_TIMEOUT=300
      - SE_GRID_TIMEOUT=300
    networks:
      - selenium

  chrome:
    image: selenium/node-chrome:4.34.0
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUB_PORT=4442
      - SE_EVENT_BUS_SUB_PORT=4443
      - SE_NODE_MAX_INSTANCES=2
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_SESSION_TIMEOUT=300
    deploy:
      replicas: 2
    networks:
      - selenium

  firefox:
    image: selenium/node-firefox:4.34.0
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUB_PORT=4442
      - SE_EVENT_BUS_SUB_PORT=4443
      - SE_NODE_MAX_INSTANCES=2
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_SESSION_TIMEOUT=300
    deploy:
      replicas: 2
    networks:
      - selenium

  edge:
    image: selenium/node-edge:4.34.0
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUB_PORT=4442
      - SE_EVENT_BUS_SUB_PORT=4443
      - SE_NODE_MAX_INSTANCES=2
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_SESSION_TIMEOUT=300
    deploy:
      replicas: 1
    networks:
      - selenium

networks:
  selenium:
    driver: bridge
